### ISSUE TITLE
Crash-1 (FIXED)

### ISSUE THREAD

**Issue by AlienzDNA** [PuzzeledImposter/Imposter#1]
The binaries stopped loading
So i dont know the fix, but i will fix it
----------------------------------------------------
Edit: You have to compulsory do npm i discord.js while having no internet fluctuations

**Comment by PuzzeledImposter** [comment]
> ## The binaries stopped loading
> So i dont know the fix, but i will fix it
> Edit: You have to compulsory do npm i discord.js while having no internet fluctuations
